# -*- coding: utf-8 -*-
"""UK_usedCars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FyZdiz8gwWPQKLE00GEXpF8clzUdfQ3T
"""

from google.colab import files
files.upload()

import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('./cars_dataset.csv')
df

sns.barplot(x = 'Make', y = 'price', data = df)

sns.lmplot(x = 'year', y = 'price', data = df, col = 'Make', hue = 'transmission')

sns.lmplot(x = 'price', y = 'mileage', data = df, col = 'transmission', hue = 'fuelType')