# -*- coding: utf-8 -*-
"""UK_usedCars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FyZdiz8gwWPQKLE00GEXpF8clzUdfQ3T
"""

from google.colab import files
files.upload()

import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('./cars_dataset.csv')
df['avgPrice'] = df.groupby('model')['price'].transform('mean')
df

temp = df['model'].tolist()
temp1 = []

for char in temp:
  if char not in temp1:
    temp1.append(char)

# Keep
sns.barplot(x = 'Make', y = 'price', data = df)

# Keep
sns.lmplot(x = 'year', y = 'price', data = df, col = 'Make', hue = 'fuelType', truncate = False, height = 10, col_wrap = 2)

# Flatter regression lines indicate more stable resale value of the car the older it is, whereas steeper slopes indicate higher loss in value the older the car, separated by fuelType and Make.

# Switch for new plot?
sns.lmplot(x = 'mileage', y = 'price', data = df, col = 'Make', hue = 'transmission', truncate = False, col_wrap = 2, height = 5, aspect = 0.75)

# The flatter the regression line, the more stable a vehicles value is in reference to the mileage of the vehicle, separated by transmission and Make.